image: gitpod/workspace-base:latest

tasks:
  - name: Install boost library
    init: |
      apt-get update
      apt-get install -y libboost-all-dev

# --------------------------------------------------------
# exposing ports for liveserve
ports:
  - port: 5500
    onOpen: notify

# --------------------------------------------------------
# some useful extensions to have
vscode:
  extensions:
    - eamodio.gitlens
    - njpwerner.autodocstring
    - lextudio.restructuredtext
    - ritwickdey.liveserver
    - ms-python.python
    - yzhang.markdown-all-in-one
    - bungcip.better-toml
    - mhutchie.git-graph
    - formulahendry.code-runner
    - PureDevSoftware.FastFind
    - SonarSource.SonarLintforVisualStudio2019
    - ms-vscode.cpptools
    - ms-vscode.cpptools-extension-pack
    - hars.CppSnippets
    - jbenden.c-cpp-flylint
    - ms-vscode.cpptools-themes
    - esbenp.prettier-vscode
    - DevartSoftware.CodeCompare
    
# --------------------------------------------------------
# using prebuilds for the container - note: atm this only
# works for the SciPy repo
# With this configuration the prebuild will happen on push to master 
github:
  prebuilds:
    # enable for master branch
    master: true
    # enable for other branches (defaults to false) 
    branches: false
    # enable for pull requests coming from this repo (defaults to true) 
    pullRequests: false
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: false
    # add a check to pull requests (defaults to true)
    addCheck: false
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: false
    
 
